config/routes.rb
Rails.application.routes.draw do
  resources :trial_employees
  devise_for :users
  resources :trials
  resources :reports
  resources :damages
  resources :properties
  resources :employees
  resources :policemen
  resources :police_stations
  resources :defendants
  resources :complainants
  resources :people
  resources :addresses
  resources :cities
  resources :provinces
  resources :categories
  root 'reports#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :city
  validates :street, :number, :presence => true
  paginates_per 5
  def direccion
    street + " " + number.to_s
  end
end

app/models/category.rb
class Category < ApplicationRecord
  paginates_per 5
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :province
  validates :name, :presence => true
  validates :name, :uniqueness => true
  paginates_per 5
end

app/models/complainant.rb
class Complainant < ApplicationRecord
  belongs_to :person
  paginates_per 5
  def person_full_name
    person.nombre_completo
  end
end

app/models/damage.rb
class Damage < ApplicationRecord
  belongs_to :person
  belongs_to :property
  paginates_per 5
end

app/models/defendant.rb
class Defendant < ApplicationRecord
  belongs_to :person
  paginates_per 5
  def person_full_name
    person.nombre_completo
  end
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :person
  paginates_per 5
  has_and_belongs_to_many :trials
  def person_full_name
    person.nombre_completo
  end
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :address
  has_one :complainant
  paginates_per 5
  def nombre_completo
    first_name + " " + last_name
  end
end

app/models/police_station.rb
class PoliceStation < ApplicationRecord
  belongs_to :address
  validates :name, :uniqueness => true
  validates :name, :presence => true
  paginates_per 5
end

app/models/policeman.rb
class Policeman < ApplicationRecord
  belongs_to :person
  belongs_to :police_station
  paginates_per 5
  def person_full_name
    person.nombre_completo
  end
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :address
  paginates_per 5
  def propiedad
    address.direccion + ", " + details
  end
end

app/models/province.rb
class Province < ApplicationRecord
  validates :name, :presence => true
  validates :name, :uniqueness => true
  paginates_per 5
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :policeman
  belongs_to :complainant
  belongs_to :defendant
  belongs_to :category
  belongs_to :damage
  paginates_per 5
end

app/models/trial.rb
class Trial < ApplicationRecord
  belongs_to :report
  has_and_belongs_to_many :employees
  paginates_per 5
end

app/models/trial_employee.rb
class TrialEmployee < ApplicationRecord
  belongs_to :employee
  belongs_to :trial
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable, :Recoverable
  devise :database_authenticatable, :registerable, :rememberable, :validatable
end

app/controllers/damages_controller.rb
class DamagesController < ApplicationController
  before_action :set_damage, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /damages or /damages.json
  def index
    @damages = Damage.all
    @damages = @damages.where(["table_type LIKE :filter", :filter => "%" + params[:filter] + "%"]) unless params[:filter].blank?
    @damages = @damages.page(params[:page]) || 1
  end

  # GET /damages/1 or /damages/1.json
  def show
  end

  # GET /damages/new
  def new
    @damage = Damage.new
  end

  # GET /damages/1/edit
  def edit
  end

  # POST /damages or /damages.json
  def create
    @damage = Damage.new(damage_params)

    respond_to do |format|
      if @damage.save
        format.html { redirect_to @damage, notice: "Daño creado con éxito." }
        format.json { render :show, status: :created, location: @damage }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @damage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /damages/1 or /damages/1.json
  def update
    respond_to do |format|
      if @damage.update(damage_params)
        format.html { redirect_to @damage, notice: "Daño actualizado con éxito." }
        format.json { render :show, status: :ok, location: @damage }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @damage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /damages/1 or /damages/1.json
  def destroy
    @damage.destroy
    respond_to do |format|
      format.html { redirect_to damages_url, notice: "Daño eliminado con éxito." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_damage
      @damage = Damage.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def damage_params
      params.require(:damage).permit(:table_type, :person_id, :property_id)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/damages_helper.rb
module DamagesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/trials_helper.rb
module TrialsHelper
end

app/views/damages/_form.html.erb
<%= form_with(model: damage) do |form| %>
  <% if damage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(damage.errors.count, "error") %> prohibited this damage from being saved:</h2>

      <ul>
        <% damage.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :table_type, 'Tipo', class: "form-label" %>
    <%= form.text_field :table_type, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :person_id, 'Persona', class: "form-label" %>
    <%= form.collection_select :person_id, Person.all, :id, :nombre_completo, { :include_blank => true }, {class: 'form-select'} %>
  </div>

  <div class="field">
    <%= form.label :property_id, 'Propiedad', class: "form-label" %>
    <%= form.collection_select :property_id, Property.all, :id, :propiedad, { :include_blank => true }, {class: 'form-select'} %>
  </div>

  <div class="actions">
    <%= form.submit 'Guardar cambios', class: "btn btn-success" %>
  </div>
<% end %>

app/views/damages/edit.html.erb
<h1>Editar Daño</h1>

<%= render 'form', damage: @damage %>

<%= link_to 'Ver', @damage %> |
<%= link_to 'Volver', damages_path %>

app/views/damages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Daños</h1>

<form method="GET" action="/damages">
  <input type="text" name="filter" class="form-control"/>
  <br>
  <input type="submit" class="btn btn-secondary" value="Buscar" />
</form>
<br>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Tipo</th>
      <th scope="col">Persona</th>
      <th scope="col">Propiedad</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @damages.each do |damage| %>
      <tr>
        <td><%= damage.table_type %></td>
        <td><%= damage.person.nombre_completo %></td>
        <td><%= damage.property.address.direccion %></td>
        <td><%= link_to 'Ver', damage, class: "btn btn-success", style: "color:white" %></td>
        <td><%= link_to 'Editar', edit_damage_path(damage), class: "btn btn-primary", style: "color:white" %></td>
        <td><%= link_to 'Eliminar', damage, class: "btn btn-danger", style: "color:white", method: :delete, data: { confirm: '¿Está seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @damages %>

<br>

<%= link_to 'Nuevo Daño', new_damage_path, class: "btn btn-primary", style: "color:white" %>

app/views/damages/new.html.erb
<h1>Nuevo Daño</h1>

<%= render 'form', damage: @damage %>

<%= link_to 'Volver', damages_path %>

app/views/damages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tipo:</strong>
  <%= @damage.table_type %>
</p>

<p>
  <strong>Persona:</strong>
  <%= @damage.person.nombre_completo %>
</p>

<p>
  <strong>Propiedad:</strong>
  <%= @damage.property.address.direccion %>
</p>

<%= link_to 'Editar', edit_damage_path(@damage) %> |
<%= link_to 'Volver', damages_path %>