config/routes.rb
Rails.application.routes.draw do
  resources :trial_employees
  devise_for :users
  resources :trials
  resources :reports
  resources :damages
  resources :properties
  resources :employees
  resources :policemen
  resources :police_stations
  resources :defendants
  resources :complainants
  resources :people
  resources :addresses
  resources :cities
  resources :provinces
  resources :categories
  root 'reports#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :city
  validates :street, :number, :presence => true
  paginates_per 5
  def direccion
    street + " " + number.to_s
  end
end

app/models/category.rb
class Category < ApplicationRecord
  paginates_per 5
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :province
  validates :name, :presence => true
  validates :name, :uniqueness => true
  paginates_per 5
end

app/models/complainant.rb
class Complainant < ApplicationRecord
  belongs_to :person
  paginates_per 5
  def person_full_name
    person.nombre_completo
  end
end

app/models/damage.rb
class Damage < ApplicationRecord
  belongs_to :person
  belongs_to :property
  paginates_per 5
end

app/models/defendant.rb
class Defendant < ApplicationRecord
  belongs_to :person
  paginates_per 5
  def person_full_name
    person.nombre_completo
  end
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :person
  paginates_per 5
  has_and_belongs_to_many :trials
  def person_full_name
    person.nombre_completo
  end
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :address
  has_one :complainant
  paginates_per 5
  def nombre_completo
    first_name + " " + last_name
  end
end

app/models/police_station.rb
class PoliceStation < ApplicationRecord
  belongs_to :address
  validates :name, :uniqueness => true
  validates :name, :presence => true
  paginates_per 5
end

app/models/policeman.rb
class Policeman < ApplicationRecord
  belongs_to :person
  belongs_to :police_station
  paginates_per 5
  def person_full_name
    person.nombre_completo
  end
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :address
  paginates_per 5
  def propiedad
    address.direccion + ", " + details
  end
end

app/models/province.rb
class Province < ApplicationRecord
  validates :name, :presence => true
  validates :name, :uniqueness => true
  paginates_per 5
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :policeman
  belongs_to :complainant
  belongs_to :defendant
  belongs_to :category
  belongs_to :damage
  paginates_per 5
end

app/models/trial.rb
class Trial < ApplicationRecord
  belongs_to :report
  has_and_belongs_to_many :employees
  paginates_per 5
end

app/models/trial_employee.rb
class TrialEmployee < ApplicationRecord
  belongs_to :employee
  belongs_to :trial
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable, :Recoverable
  devise :database_authenticatable, :registerable, :rememberable, :validatable
end

app/controllers/police_stations_controller.rb
class PoliceStationsController < ApplicationController
  before_action :set_police_station, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /police_stations or /police_stations.json
  def index
    @police_stations = PoliceStation.all
    @police_stations = @police_stations.where(["name LIKE :filter", :filter => "%" + params[:filter] + "%"]) unless params[:filter].blank?
    @police_stations = @police_stations.page(params[:page]) || 1
  end

  # GET /police_stations/1 or /police_stations/1.json
  def show
  end

  # GET /police_stations/new
  def new
    @police_station = PoliceStation.new
  end

  # GET /police_stations/1/edit
  def edit
  end

  # POST /police_stations or /police_stations.json
  def create
    @police_station = PoliceStation.new(police_station_params)

    respond_to do |format|
      if @police_station.save
        format.html { redirect_to @police_station, notice: "Comisaría creada con éxito." }
        format.json { render :show, status: :created, location: @police_station }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @police_station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /police_stations/1 or /police_stations/1.json
  def update
    respond_to do |format|
      if @police_station.update(police_station_params)
        format.html { redirect_to @police_station, notice: "Comisaría actualizada con éxito" }
        format.json { render :show, status: :ok, location: @police_station }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @police_station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /police_stations/1 or /police_stations/1.json
  def destroy
    @police_station.destroy
    respond_to do |format|
      format.html { redirect_to police_stations_url, notice: "Comisaría eliminada con éxito." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_police_station
      @police_station = PoliceStation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def police_station_params
      params.require(:police_station).permit(:address_id, :name)
    end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/damages_helper.rb
module DamagesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/police_stations_helper.rb
module PoliceStationsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/trials_helper.rb
module TrialsHelper
end

app/views/police_stations/_form.html.erb
<%= form_with(model: police_station) do |form| %>
  <% if police_station.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(police_station.errors.count, "error") %> prohibited this police_station from being saved:</h2>

      <ul>
        <% police_station.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :address_id, 'Dirección', class: "form-label" %>
    <%= form.collection_select :address_id, Address.all, :id, :direccion, { :include_blank => true }, {class: 'form-select'} %>
  </div>

  <div class="field">
    <%= form.label :name, 'Nombre', class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit 'Guardar cambios', class: "btn btn-success" %>
  </div>
<% end %>

app/views/police_stations/edit.html.erb
<h1>Editar Comisaría</h1>

<%= render 'form', police_station: @police_station %>

<%= link_to 'Ver', @police_station %> |
<%= link_to 'Volver', police_stations_path %>

app/views/police_stations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comisarías</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Dirección</th>
      <th scope="col">Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @police_stations.each do |police_station| %>
      <tr>
        <td><%= police_station.address.direccion %></td>
        <td><%= police_station.name %></td>
        <td><%= link_to 'Ver', police_station, class: "btn btn-success", style: "color:white" %></td>
        <td><%= link_to 'Editar', edit_police_station_path(police_station), class: "btn btn-primary", style: "color:white" %></td>
        <td><%= link_to 'Eliminar', police_station, class: "btn btn-danger", style: "color:white", method: :delete, data: { confirm: '¿Está seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @police_stations %>

<br>

<%= link_to 'Nueva Comisaría', new_police_station_path, class: "btn btn-primary", style: "color:white" %>

app/views/police_stations/new.html.erb
<h1>Nueva Comisaría</h1>

<%= render 'form', police_station: @police_station %>

<%= link_to 'Volver', police_stations_path %>

app/views/police_stations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Dirección:</strong>
  <%= @police_station.address.direccion %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @police_station.name %>
</p>

<%= link_to 'Editar', edit_police_station_path(@police_station) %> |
<%= link_to 'Volver', police_stations_path %>