config/routes.rb
Rails.application.routes.draw do
  resources :trial_employees
  devise_for :users
  resources :trials
  resources :reports
  resources :damages
  resources :properties
  resources :employees
  resources :policemen
  resources :police_stations
  resources :defendants
  resources :complainants
  resources :people
  resources :addresses
  resources :cities
  resources :provinces
  resources :categories
  root 'reports#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :city
  validates :street, :number, :presence => true
  paginates_per 5
  def direccion
    street + " " + number.to_s
  end
end

app/models/category.rb
class Category < ApplicationRecord
  paginates_per 5
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :province
  validates :name, :presence => true
  validates :name, :uniqueness => true
  paginates_per 5
end

app/models/complainant.rb
class Complainant < ApplicationRecord
  belongs_to :person
  paginates_per 5
  def person_full_name
    person.nombre_completo
  end
end

app/models/damage.rb
class Damage < ApplicationRecord
  belongs_to :person
  belongs_to :property
  paginates_per 5
end

app/models/defendant.rb
class Defendant < ApplicationRecord
  belongs_to :person
  paginates_per 5
  def person_full_name
    person.nombre_completo
  end
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :person
  paginates_per 5
  has_and_belongs_to_many :trials
  def person_full_name
    person.nombre_completo
  end
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :address
  has_one :complainant
  paginates_per 5
  def nombre_completo
    first_name + " " + last_name
  end
end

app/models/police_station.rb
class PoliceStation < ApplicationRecord
  belongs_to :address
  validates :name, :uniqueness => true
  validates :name, :presence => true
  paginates_per 5
end

app/models/policeman.rb
class Policeman < ApplicationRecord
  belongs_to :person
  belongs_to :police_station
  paginates_per 5
  def person_full_name
    person.nombre_completo
  end
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :address
  paginates_per 5
  def propiedad
    address.direccion + ", " + details
  end
end

app/models/province.rb
class Province < ApplicationRecord
  validates :name, :presence => true
  validates :name, :uniqueness => true
  paginates_per 5
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :policeman
  belongs_to :complainant
  belongs_to :defendant
  belongs_to :category
  belongs_to :damage
  paginates_per 5
end

app/models/trial.rb
class Trial < ApplicationRecord
  belongs_to :report
  has_and_belongs_to_many :employees
  paginates_per 5
end

app/models/trial_employee.rb
class TrialEmployee < ApplicationRecord
  belongs_to :employee
  belongs_to :trial
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable, :Recoverable
  devise :database_authenticatable, :registerable, :rememberable, :validatable
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /reports or /reports.json
  def index
    @reports = Report.all
    @reports = @reports.page(params[:page]) || 1
  end

  # GET /reports/1 or /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports or /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: "Denuncia creada con éxito." }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1 or /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: "Denuncia actualizada con éxito." }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1 or /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: "Denuncia eliminada con éxito." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def report_params
      params.require(:report).permit(:date, :details, :policeman_id, :complainant_id, :defendant_id, :category_id, :damage_id)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/damages_helper.rb
module DamagesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/trials_helper.rb
module TrialsHelper
end

app/views/reports/_form.html.erb
<%= form_with(model: report) do |form| %>
  <% if report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
        <% report.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date, 'Fecha y hora', class: "form-label" %>
    <%= form.datetime_select :date %>
  </div>

  <div class="field">
    <%= form.label :details, 'Detalles', class: "form-label" %>
    <%= form.text_field :details, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :policeman_id, 'Policía a cargo de la denuncia', class: "form-label" %>
    <%= form.collection_select :policeman_id, Policeman.all, :id, :person_full_name, { :include_blank => true }, {class: 'form-select'} %>
  </div>

  <div class="field">
    <%= form.label :complainant_id, 'Denunciante', class: "form-label" %>
    <%= form.collection_select :complainant_id, Complainant.all, :id, :person_full_name, { :include_blank => true }, {class: 'form-select'} %>
  </div>

  <div class="field">
    <%= form.label :defendant_id, 'Acusado', class: "form-label" %>
    <%= form.collection_select :defendant_id, Defendant.all, :id, :person_full_name, { :include_blank => true }, {class: 'form-select'} %>
  </div>

  <div class="field">
    <%= form.label :category_id, 'Categoría de la denuncia', class: "form-label" %>
    <%= form.collection_select :category_id, Category.all, :id, :name, { :include_blank => true }, {class: 'form-select'} %>
  </div>

  <div class="field">
    <%= form.label :damage_id, 'Tipo de daño', class: "form-label" %>
    <%= form.collection_select :damage_id, Damage.all, :id, :table_type, { :include_blank => true }, {class: 'form-select'} %>
  </div>

  <div class="actions">
    <%= form.submit 'Guardar Cambios', class: "btn btn-success" %>
  </div>
<% end %>

app/views/reports/edit.html.erb
<h1>Editar Denuncia</h1>

<%= render 'form', report: @report %>

<%= link_to 'Ver', @report %> |
<%= link_to 'Volver', reports_path %>

app/views/reports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Denuncias</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Fecha y hora</th>
      <th scope="col">Detalles</th>
      <th scope="col">Policía encargado</th>
      <th scope="col">Denunciante</th>
      <th scope="col">Acusado</th>
      <th scope="col">Categoría</th>
      <th scope="col">Tipo de daño</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.date %></td>
        <td><%= report.details %></td>
        <td><%= report.policeman.person_full_name %></td>
        <td><%= report.complainant.person_full_name %></td>
        <td><%= report.defendant.person_full_name %></td>
        <td><%= report.category.name %></td>
        <td><%= report.damage.table_type %></td>
        <td><%= link_to 'Ver', report, class: "btn btn-success", style: "color:white" %></td>
        <td><%= link_to 'Editar', edit_report_path(report), class: "btn btn-primary", style: "color:white" %></td>
        <td><%= link_to 'Eliminar', report, class: "btn btn-danger", style: "color:white", method: :delete, data: { confirm: '¿Está seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @reports %>

<br>

<%= link_to 'Nueva Denuncia', new_report_path, class: "btn btn-primary", style: "color:white" %>

app/views/reports/new.html.erb
<h1>Nueva Denuncia</h1>

<%= render 'form', report: @report %>

<%= link_to 'Volver', reports_path %>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fecha y hora:</strong>
  <%= @report.date %>
</p>

<p>
  <strong>Detalles:</strong>
  <%= @report.details %>
</p>

<p>
  <strong>Policía a cargo de la denuncia:</strong>
  <%= @report.policeman.person_full_name %>
</p>

<p>
  <strong>Denunciante:</strong>
  <%= @report.complainant.person_full_name %>
</p>

<p>
  <strong>Acusado:</strong>
  <%= @report.defendant.person_full_name %>
</p>

<p>
  <strong>Categoría:</strong>
  <%= @report.category.name %>
</p>

<p>
  <strong>Tipo de daño:</strong>
  <%= @report.damage.table_type %>
</p>

<%= link_to 'Editar', edit_report_path(@report) %> |
<%= link_to 'Volver', reports_path %>